name: Build

on:
  # Build on new commits or pull requests.
  push:
  pull_request:
  schedule:
    # Run every week just to make sure the CI environment still works.
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Compile
      run: dotnet build -c Release
